name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: test
      run: cd src;
           python3 -u ./cluster.py -g all > ../etc/out/cluster.out
    - run: grep -q fail ../etc/out/cluster.out &&  exit -1 || echo "This job's status is success."
